import type { Scope } from '../game/model';
export const arrival = [
  { id: 'sofa', label: 'Sit', x: 403, y: 370, scope: 'personal' as Scope, title: 'Sofa', text: '' },
  { id: 'armchair', label: 'Sit', x: 605, y: 450, scope: 'personal' as Scope, title: 'Armchair', text: '' },
  { id: 'stove', label: 'Use stove', x: 648, y: 322, scope: 'shared_world' as Scope, title: 'Stove', text: '' },
  { id: 'sink', label: 'Use sink', x: 276, y: 316, scope: 'shared_world' as Scope, title: 'Sink', text: '' },
  { id: 'worktop', label: 'Recipes', x: 500, y: 440, scope: 'personal' as Scope, title: 'Recipe book', text: '' },
  { id: 'journal', label: 'Read your daily journal', x: 386, y: 294, scope: 'personal' as Scope,
    title: 'Yesterday at the castle', text: 'A record of the household and your own day.' },
  { id: 'door-left', label: 'Enter Player 1 bedroom', x: 223, y: 230, scope: 'personal' as Scope,
    title: 'The west bedroom', text: 'The quiet room on the left.' },
  { id: 'door-right', label: 'Enter Player 2 bedroom', x: 683, y: 230, scope: 'personal' as Scope,
    title: 'The east bedroom', text: 'The quiet room on the right.' },
  { id: 'letter', label: 'Read the sealed letter', x: 330, y: 275, scope: 'personal' as Scope,
    title: 'A letter that waited', text: 'The paper smells faintly of orange peel. "If the house lets you in, leave a light burning. Some memories need a way home." Beneath the signature, someone has pressed a ring of six tiny spoons into the wax.' },
  { id: 'hearth', label: 'Light the household hearth', x: 552, y: 265, scope: 'shared_world' as Scope,
    title: 'The house exhales', text: 'Amber light runs through the cold ironwork. Somewhere upstairs, a door stops rattling. Whoever else comes to live here will find this warmth waiting.' },
  { id: 'pantry', label: 'Open your welcome parcel', x: 785, y: 300, scope: 'personal' as Scope,
    title: 'A practical welcome', text: 'Three cacao beans, wrapped in a flour sack. The note reads: "The forge opens in the morning. Bring the broken latch, not the whole door. — Rook"' },
  { id: 'bed', label: 'Rest', x: 210, y: 345, scope: 'personal' as Scope,
    title: 'Bed', text: '' },
  { id: 'desk', label: 'Open journal', x: 382, y: 289, scope: 'personal' as Scope,
    title: 'Daily journal', text: '' },
  { id: 'bookshelf', label: 'Open recipes', x: 132, y: 232, scope: 'personal' as Scope,
    title: 'Recipe book', text: '' },
  { id: 'chest', label: 'Open storage', x: 804, y: 415, scope: 'personal' as Scope,
    title: 'Household chest', text: '' },
  { id: 'plant', label: 'Moonfern', x: 842, y: 347, scope: 'personal' as Scope,
    title: 'Moonfern', text: '' },
  { id: 'side-table', label: 'Bedside table', x: 272, y: 446, scope: 'personal' as Scope,
    title: 'Bedside table', text: '' },
  { id: 'window-west', label: 'West window', x: 270, y: 218, scope: 'personal' as Scope,
    title: 'West window', text: '' },
  { id: 'window-east', label: 'East window', x: 680, y: 218, scope: 'personal' as Scope,
    title: 'East window', text: '' },
  { id: 'candle-desk', label: 'Tend the desk candle', x: 382, y: 289, scope: 'shared_world' as Scope,
    title: 'The desk candle', text: 'A small flame changes the shape of the room. Its light belongs to everyone in the house.' },
  { id: 'candle-table', label: 'Tend the bedside candle', x: 272, y: 446, scope: 'shared_world' as Scope,
    title: 'The bedside candle', text: 'The brass dish is warm beneath your fingers. You tend the wick and watch the shadows settle.' },
  { id: 'door-out', label: 'Open the door to the landing', x: 685, y: 258, scope: 'personal' as Scope,
    title: 'The castle landing', text: 'A cool draft carries the smell of stone and rain.' },
  { id: 'door-home', label: 'Return to your room', x: 480, y: 258, scope: 'personal' as Scope,
    title: 'Your room', text: 'The familiar floorboards give beneath your feet.' },
  { id: 'landing-stairs', label: 'Retired stair', x: 800, y: 456, scope: 'personal' as Scope,
    title: 'Retired stair', text: '' },
] as const;
export type ArrivalId = typeof arrival[number]['id'];
export function validateContent() {
  const ids = arrival.map(entry => entry.id);
  if (new Set(ids).size !== ids.length) throw Error('Duplicate arrival content ID');
}
